  AWSTemplateFormatVersion: "2010-09-09"

  Description: "Creates Launch Configuration with Web Server, Elastic
  Load Balancer and Auto Scaling Group in Private subnet0"

  Parameters:
    VPCStackName:
      Type: String
      Default: DevVPC
      MinLength: 1
      AllowedValues:
        - DevVPC
        - ProdVPC
    KeyName:
      Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
      Type: 'AWS::EC2::KeyPair::KeyName'
      Default: imaki_NVirginia
      ConstraintDescription: must be the name of an existing EC2 KeyPair.
    SSHLocation:
      Description: The IP address range that can be used to SSH to the EC2 instances
      Type: String
      Default: 0.0.0.0/0
      ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    InstanceType:
      Type: String
      Description: Type of EC2 instance.
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - t2.small
        - t2.medium
      ConstraintDescription: Must be a valid EC2 instance type.

  Mappings:
    RegionMap:
      us-east-1:
        AMI: ami-07d0cf3af28718ef8 # Ubuntu Server 18.04 LTS

  Resources:
    WebServerSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Enable SSH access via port 22 and HTTP via port 80
        VpcId:
          Fn::ImportValue: "DevVPC-VPCId"
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: !Ref SSHLocation
          - IpProtocol: tcp
            FromPort: '80'
            ToPort: '80'
            CidrIp: 0.0.0.0/0

    LaunchConfig:
      Type: "AWS::AutoScaling::LaunchConfiguration"
      Properties:
        AssociatePublicIpAddress: "false"
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroups:
          - !Ref WebServerSecurityGroup

    WebServerAutoScalingGroup:
      Type: "AWS::AutoScaling::AutoScalingGroup"
      Properties:
        VPCZoneIdentifier:
          - Fn::ImportValue: "DevVPC-PrivateSubnet0"
        LaunchConfigurationName: !Ref LaunchConfig
        MinSize: "3"
        MaxSize: "5"
        DesiredCapacity: "3"
        Tags:
          - Key: "Name"
            Value: A3-ASG-web
            PropagateAtLaunch: true
