# Creates an ASG 1:1 for Jenkins, attaching or creating persistent volume.
#
# aws cloudformation deploy --template-file jenkins.yml --stack-name jenkins --parameter-overrides VPCStackName=DevVPC MountScriptVersion=0.0.1 PuppetScriptVersion=0.0.1 --capabilities CAPABILITY_IAM
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the SSH keypair to use for the EC2 instances.
    Default: devopsa3

  VPCStackName:
    Type: String
    MinLength: 1

  InstanceType:
    Type: String
    Description: Type of EC2 instance
    Default: t2.micro
    ConstraintDescription: Must be a valid EC2 instance type.

  S3Path:
    Type: String
    Description: The S3 path
    Default: devopsa3

  MountScriptVersion:
    Type: String
    Description: Bootstrap script version for mounting volume

  PuppetScriptVersion:
    Type: String
    Description: Bootstrap script version

  Service:
    Type: String
    Description: lifecycle policy tag
    Default: jenkins

  Environment:
    Type: String
    Description: Normally - ci
    Default: ci

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0b69ea66ff7391e80
    us-west-1:
      AMI: ami-0245d318c6788de52

Resources:
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${VPCStackName}-VPCId"
      GroupDescription: SSH, HTTP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0

  JenkinsRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyName: Jenkins
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - iam:CreateInstanceProfile
                  - iam:CreateRole
                  - iam:DeleteRolePolicy
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:PassRole
                  - autoscaling:CreateLaunchConfiguration
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:CreateAutoScalingGroup
                  - autoscaling:UpdateAutoScalingGroup
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeScalingActivities
                  - autoscaling:PutScalingPolicy
                  - autoscaling:DeletePolicy
                  - autoscaling:DeleteAutoScalingGroup
                  - autoscaling:DeleteLaunchConfiguration
                  - ec2:DescribeTags
                  - ec2:DescribeSnapshots
                  - ec2:DescribeVolumes
                  - ec2:DescribeAddresses
                  - ec2:DescribeKeyPairs
                  - ec2:CreateVolume
                  - ec2:CreateTags
                  - ec2:AttachVolume
                  - ec2:AssociateAddress
                  - ec2:CreateSecurityGroup
                  - ec2:DescribeSecurityGroups
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:DescribeAccountAttributes
                  - ec2:DeleteSecurityGroup
                  - ssm:UpdateInstanceInformation

  JenkinsProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: JenkinsRole

  JenkinsLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      IamInstanceProfile: !Ref JenkinsProfile
      KeyName: !Ref KeyPairName
      SecurityGroups:
      - Ref: JenkinsSecurityGroup
      InstanceType: !Ref InstanceType
      AssociatePublicIpAddress: True
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            function retryCommand() {
                local ATTEMPTS="$1"
                local SLEEP="$2"
                local COMMAND="$3"
                for i in $(seq 1 $ATTEMPTS); do
                    [ $i == 1 ] || sleep $SLEEP
                    eval $COMMAND && echo $? && break || echo $?
                done
            }
            function retryPuppetCommand() {
                local ATTEMPTS="$1"
                local SLEEP="$2"
                local COMMAND="$3"
                for i in $(seq 1 $ATTEMPTS); do
                    [ $i == 1 ] || sleep $SLEEP
                    $COMMAND
                    if [ $? -eq 2 ]
                    then
                      echo "Success"
                      break
                    else
                      echo $?
                    fi
                done
            }
            retryCommand 5 10 'aws s3 cp "s3://${S3Path}/scripts/jenkins/mount_volume-${ver}.sh" - | bash -l -s -- --hostname jenkins'
            rpm -Uvh https://yum.puppet.com/puppet5-release-el-7.noarch.rpm
            yum -y update
            retryCommand 5 10 'yum install -y puppet-agent'
            export PATH=$PATH:/opt/aws/bin/:/opt/puppetlabs/bin/:/opt/puppetlabs/puppet/bin/
            retryCommand 5 10  'aws s3 cp "s3://${S3Path}/scripts/puppet-${pupver}.tar" .'
            tar -C /etc/puppetlabs/ -xvf puppet-${pupver}.tar
            retryCommand 5 10 'gem install r10k'
            retryCommand 5 10 'r10k puppetfile install --puppetfile=/etc/puppetlabs/Puppetfile'
            retryPuppetCommand 5 10 'puppet apply --test /etc/puppetlabs/code/environments/production/manifests/site.pp'
            sleep 30
            curl -sS http://localhost:8080
            cfn-signal -e $? --stack ${AWS::StackName} --resource JenkinsAutoScalingGroup --region ${AWS::Region}
          - ver: !Ref MountScriptVersion
            pupver: !Ref PuppetScriptVersion

  JenkinsAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${VPCStackName}-PublicSubnet0"
      LaunchConfigurationName: !Ref JenkinsLaunchConfig
      MinSize: '1'
      MaxSize: '1'
      TargetGroupARNs:
        - Fn::ImportValue: alb-tgJenkins-ARN
      Tags:
        - Key: 'Name'
          Value: 'Jenkins'
          PropagateAtLaunch: true
        - Key: 'Environment'
          Value: !Ref Environment
          PropagateAtLaunch: true
        - Key: 'Service'
          Value: !Ref Service
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT20M"
