---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Public and private DNS zone'

Parameters:
  PrivateDomainName:
    Description: 'The name of the domain via private interface'
    Type: String
    Default: example.com

  PublicDomainName:
    Description: 'The name of the domain via public interface'
    Type: String
    Default: devopsa3train.co.uk

  VPCStackNameToAssociate:
    Type: String
    MinLength: 1

Resources:
  PrivateHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${PrivateDomainName} private DNS zone"
      Name: !Ref PrivateDomainName
      VPCs:
      - VPCId: {'Fn::ImportValue': !Sub '${VPCStackNameToAssociate}-VPCId'}
        VPCRegion: {'Fn::ImportValue': !Sub '${VPCStackNameToAssociate}-Region'}

  PublicHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${PublicDomainName} public DNS zone"
      Name: !Ref PublicDomainName

Outputs:
  PrivateZoneName:
    Description: 'The name of the private hosted zone.'
    Value: !Ref PrivateDomainName
    Export:
      Name: !Sub '${AWS::StackName}-PrivateZoneName'

  PrivateZoneId:
    Description: 'The ID of the private hosted zone.'
    Value: !Ref PrivateHostedZone
    Export:
      Name: !Sub '${AWS::StackName}-PrivateZoneId'

  PublicZoneName:
    Description: 'The name of the public hosted zone.'
    Value: !Ref PublicDomainName
    Export:
      Name: !Sub '${AWS::StackName}-PublicZoneName'

  PublicZoneId:
    Description: 'The ID of the public hosted zone.'
    Value: !Ref PublicHostedZone
    Export:
      Name: !Sub '${AWS::StackName}-PublicZoneId'
