AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a VPC that and then creates a peering connection with an existing
  VPC that you specify.
Parameters:
  DevVPCStackName:
    Type: String
    Default: DevVPC
    MinLength: 1

  ProdVPCStackName:
    Type: String
    Default: ProdVPC
    MinLength: 1

Resources:
  myVPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerRegion:
        Fn::ImportValue: !Sub "${ProdVPCStackName}-Region"
      VpcId: 
        Fn::ImportValue: !Sub "${DevVPCStackName}-VPCId"
      PeerVpcId:
        Fn::ImportValue: !Sub "${ProdVPCStackName}-VPCId"
  PeeringRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 
        Fn::ImportValue: !Sub "${ProdVPCStackName}-PeerCIDRRef"
      RouteTableId:
        Fn::ImportValue: !Sub "${DevVPCStackName}-RouteTablePeerRef"
      VpcPeeringConnectionId: !Ref myVPCPeeringConnection