# For manual creation/update use:
# aws cloudformation deploy --stack-name ECR-repo --template-file ecr-repo.yml
---
AWSTemplateFormatVersion: '2010-09-09'

Description: Deploy a ECR with lifecycle policy.

Parameters:

  repositoryName:
    Type: String
    Default: 'devopsa3'
    Description: The name to use for the repository.

  registryId:
    Type: String
    Default: '054017840000'
    Description: The AWS account ID associated with the registry that contains the repository.

Resources:

  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: |
              {
                  "rules": [
                      {
                          "rulePriority": 1,
                          "description": "Rule 1",
                          "selection": {
                              "tagStatus": "tagged",
                              "tagPrefixList": ["alpha"],
                              "countType": "imageCountMoreThan",
                              "countNumber": 1
                          },
                          "action": {
                              "type": "expire"
                          }
                      },
                      {
                          "rulePriority": 2,
                          "description": "Rule 2",
                          "selection": {
                              "tagStatus": "untagged",
                              "countType": "sinceImagePushed",
                              "countUnit": "days",
                              "countNumber": 3
                          },
                          "action": {
                              "type": "expire"
                          }
                      },
                      {
                          "rulePriority": 3,
                          "description": "Rule 3",
                          "selection": {
                              "tagStatus": "any",
                              "countType": "imageCountMoreThan",
                              "countNumber": 30
                          },
                          "action": {
                              "type": "expire"
                          }
                      }
                  ]
              }
        RegistryId: !Ref registryId
      RepositoryName: !Ref repositoryName

Outputs:
  Arn:
    Value: !GetAtt MyRepository.Arn